import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./(application)/resources/globals.scss";
import AppProvider from "./(application)/components/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Task",
  description: "Generated by Amir Mohammad sanji",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
